all:
  children:
    open5gs:
      hosts:
        10.0.50.11:
          open5gs_services:
            - nrf
            - scp
        10.0.50.12:
          open5gs_services:
            - nrf
        #10.0.50.13:
        #10.0.50.14:
        #10.0.50.15:
        #10.0.50.16:

  vars:
    ansible_user: template-admin
    ansible_ssh_pass: VMware1!
    ansible_become: true
    ansible_become_pass: VMware1!
    host_key_checking: false
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
